# Travis-CI Build for dynamitey 
# see travis-ci.org for details

language: csharp
solution: Dynamitey.sln
env:
  global:
    - EnableNuGetPackageRestore=true
    - PATH=$PATH:/usr/bin
    
mono: latest
dotnet: 1.0.4
dist: trusty

install:
  - /usr/bin/env
  - ls -la /usr/bin/fsharpi

script:
  - ./build.fsx
