# Travis-CI Build for dynamitey 
# see travis-ci.org for details

language: csharp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx

solution: Dynamitey.sln
    
mono: latest
dotnet: 2.0.0

install:
  - msbuild /ver

script:
  - ./build.fsx

branches:
  only:
    - master