# Travis-CI Build for dynamitey 
# see travis-ci.org for details

language: csharp
solution: Dynamitey.sln
env:
  global:
    - EnableNuGetPackageRestore=true
    
mono: none
dotnet: 1.1.4
dist: trusty

script:
  - dotnet restore
  - dotnet build
  - .ci/nunit.sh Tests/bin/Debug/Tests.dll
